### ISSUE TITLE
App con diferentes operaciones 

### ISSUE THREAD

**Issue by Blanca-estela-valerio-rivero** [SistemasTecTlaxiaco/actividad-11-practica-de-visualizacion-de-datos-confident-students#1]
[REALIZAR UN APP QUE CONTENGA OPERACIONES DE INSERCIÓN, MODIFICACIÓN Y BORRADO DE  DATO.pdf](https://github.com/SistemasTecTlaxiaco/actividad-11-practica-de-visualizacion-de-datos-confident-students/files/15458532/REALIZAR.UN.APP.QUE.CONTENGA.OPERACIONES.DE.INSERCION.MODIFICACION.Y.BORRADO.DE.DATO.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
